### ISSUE TITLE
Demo link has an unverifed cert

### ISSUE THREAD

**Issue by sunjam** [diafygi/letsencrypt-nosudo#1]
"This Connection is Untrusted

You have asked *******\* to connect securely to letsencrypt.daylightpirates.org, but we can't confirm that your connection is secure.

Normally, when you try to connect securely, sites will present trusted identification to prove that you are going to the right place. However, this site's identity can't be verified.
What Should I Do?

If you usually connect to this site without problems, this error could mean that someone is trying to impersonate the site, and you shouldn't continue."

**Comment by diafygi** [comment]
This is intentional. The SSL certificate for letsencrypt.daylightpirates.org is signed by the Let's Encrypt demo certificate authority. The real Let's Encrypt certificate authority will be released sometime in mid-2015, at which point I will get the letsencrypt.daylightpirates.org certificate signed by that and you won't see the warning anymore.
