### ISSUE TITLE
Validate that the target domain is serving the challenge

### ISSUE THREAD

**Issue by abl** [diafygi/letsencrypt-nosudo#22]
Since letsencrypt-nosudo already requires network access it seems like step 4-N (when HTTPServer is run) could trivially validate that the correct challenge is being served and give better feedback / give the user a chance to fix things.

Common-ish errors off the top of my head:
1. Challenge served is from a previous subdomain - try again with the updated command
2. Challenge is returning a non-200 code from $WEB_SERVER - stop this web server and try again
3. Challenge is not valid JSON - is the domain behind a proxy? (iirc some Cloudflare settings rewrite things in flight.)

**Comment by diafygi** [comment]
Great issue. Yes, we could have a waiting loop that verifies the signatures and checks to see if the file is being hosted correctly,

**Comment by ecc256** [comment]
I use this (pardon my noob python, please)

```
    while True:
        url = "http://{}/.well-known/acme-challenge/{}".format(domain, token)
        try:
            resp = urllib2.urlopen(url)
            result = resp.read()
            if result == keyauthorization:
                return
            sys.stderr.write("\nGot:\n{}Need:\n{}\n".format(result, keyauthorization))
        except urllib2.HTTPError as e:
            sys.stderr.write(e.code)

        pause()
```

**Comment by JazzMaster** [comment]
I have a tweak just for this. Step 4: validation(on live server). You dont need root for this.
sign everything like usual(im doing on my local box here)
now, instead of giving the python script to run on the server, do this:
find your remote live server and ssh into it in another window

make dir(mkdir) .well-known/acme-challenge [in server root]
nano <filename>
the filename is what it asks you to run inside the python command. A zero byte file will do. type a key, delete it, then save the file.

The trick is that the filename has a period in it, but that part of the file is not actually requested.(pops a 404 on my wordpress setup), so you need to rename the file accordingly before continuing.Remove the period and everything after it.

The rest should succeed. Actually some cert servers request that you similar.All they are checking is that the domain belongs to you by telling you to serve some random filename.

No need to superseed an already running http service or server.Use whats running.Besides, shared hosts dont give you root access.

**Comment by JazzMaster** [comment]
edit: close. It looks like the filename is correct but the entire key string given in the python file is needed inside the file. so forget the period for the filename but put everything in the file.

**Comment by vinaythoke** [comment]
Hello Richard (JazzMaster),

I was also trying to install it on shared host. Provided that the shared host doesn't give me root access, the challenge step (STEP 4) was failed. 

Could you please tell me how to go about it step-by-step if you know?
What file to create?
At what time during the script execution?

I would appreciate your help.
Thank you!

**Comment by vinaythoke** [comment]
Never mind. I did it myself. 

Thank you. :)

**Comment by diafygi** [comment]
I've decided that I don't want to verify the file is being served properly. Let's Encrypt's verification will fail, so you'll see something is wrong anyway, and can retry again after you've fixed things.
