### ISSUE TITLE
Works with 2008R2 and above.

### ISSUE THREAD

**Issue by ecc256** [diafygi/letsencrypt-nosudo#24]
The only problem was tempfile.NamedTemporaryFile() opens file with non-shared access, so openssl can neither read .json nor write to .sig files.
Quick fix was to close file handle and reopen it before seek(0) so openssl can do its job

openssl errors
.sig
openssl dgst Error opening output file system library:fopen:Broken pipe:
.json
register_bpl9wi.json: Permission denied

**Comment by diafygi** [comment]
@ecc256 Can you please clarify? What is 2008R2? Also, the reason why I'm using NamedTemporaryFiles is because they will automatically disappear when an error occurs or when the program exists. If we save/reopen the files, will they still disappear if an exception is raised (e.g. if ACME's server is down or something?) or when the program exits?

**Comment by ecc256** [comment]
@diafygi,
[2008R2](https://en.wikipedia.org/wiki/Windows_Server_2008_R2) is one the Redmont OSs.
The is a [portability issue](https://bugs.python.org/issue14243) with tempfile.NamedTemporaryFile, if you don’t use Redmont stuff, you've never run into it, probably.

**Comment by diafygi** [comment]
@ecc256 Can you please try my new browser-based client (https://gethttpsforfree.com)? It doesn't use python, so it shouldn't have the Windows issues that you're having.
