### ISSUE TITLE
Does this script also record IP address?

### ISSUE THREAD

**Issue by Arlen22** [diafygi/letsencrypt-nosudo#89]
The default Let's Encrypt script has a notice about the IP address the certificate was requested from. Apparently it uses this to authenticate the source of the request or something like that. Apparently it only shows up in manual mode.

> NOTE: The IP of this machine will be publicly logged as having requested this
> certificate. If you're running certbot in manual mode on a machine that is not
> your server, please ensure you're okay with that.

Does the ACME protocol record the IP, and so this notice would also apply when using this script? Or is this a feature of Let's Encrypt?

**Comment by diafygi** [comment]
This script makes HTTPS requests to the ACME server (i.e. the Let's Encrypt certificate authority server) to request that it issue a certificate. That server will see (and possible log) your IP address, but I have no control over that since I'm not working at Let's Encrypt.

Other than that, I don't see anything you do (IP addresses, etc.) with this script since it only makes requests to the Let's Encrypt certificate authority, and not any of my servers.
